
  GRANT EXECUTE ON "OMS"."CHED_UTILS_CFG" TO "CHED_SGAMI";
  GRANT EXECUTE ON "OMS"."CHED_UTILS_CFG" TO "PO_AMI";
  GRANT EXECUTE ON "OMS"."CHED_UTILS_CFG" TO "POWERON";
  GRANT EXECUTE ON "OMS"."CHED_UTILS_CFG" TO "OMS_USER";
  GRANT EXECUTE ON "OMS"."CHED_UTILS_CFG" TO "PO_CONNECT";


